---
commitizen:
  name: cz_conventional_commits
  version: 1.2.2
  bump_message: "docs: bump version {{current_version}} → {{new_version}}"
  changelog_file: .github/CHANGELOG.md
  tag_format: $version
  update_changelog_on_bump: true
  version_scheme: semver2
