---
commitizen:
  bump_message: 'docs: bump version $current_version -> $new_version'
  changelog_file: .github/CHANGELOG.md
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 1.4.0
  version_scheme: semver2
