---
commitizen:
  name: cz_conventional_commits
  version: 1.2.1
  tag_format: $version
  update_changelog_on_bump: true
  version_scheme: semver2
  bump_message: "chore: bump version {current_version} → {new_version}"
  changelog_file: .github/CHANGELOG.md
