---
commitizen:
  name: cz_conventional_commits
  path: .github/CHANGELOG.md
  tag_format: $version
  update_changelog_on_bump: true
  version: 1.2.0
  version_scheme: semver2
  bump_message: "chore: bump version {current_version} → {new_version}"
