---
commitizen:
  bump_message: "chore: bump version {current_version} \u2192 {new_version}"
  changelog_file: .github/CHANGELOG.md
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 1.2.2
  version_scheme: semver2
