---
commitizen:
  bump_message: "chore: bump version {current_version} \u2192 {new_version}"
  name: cz_conventional_commits
  path: .github/CHANGELOG.md
  tag_format: $version
  update_changelog_on_bump: true
  version: 1.2.1
  version_scheme: semver2
