---
matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
    sources:
      - '.**/*.md'
      - '.**/**/*.md'
      - '.**/**/.**/*.md'
    default_encoding: utf-8
