---
name: "Bug Report"
description: "Report an issue with the dotfiles configuration."
labels: ["bug"]
assignees: "CelticBoozer"
title: "[Bug] "
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps required to reproduce the issue."
      placeholder: |
        1.
        2.
        3.
  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots related to the issue."
