# Remember specific matches should be first. 
# F.e. nvim running inside the kitty terminal should be first.
separator = ' '

[matching]
'/Picture-in-Picture/' = ''
'/Private Browsing/' = ''
'firefoxdeveloperedition' = ''
'/Google Chrome/' = ''
'/nvim ?\w*/' = ''
'jetbrains-idea-ce' = ''
'jetbrains-idea' = ''
'Postman' = ''
'/ranger/' = ''
'steam' = ''
'kitty' = ''
'cool-retro-term.cool-retro-term' = ''
'obsidian' = ''
'mpv' = ''
'org.telegram.desktop' = ''
'com.viber.Viber' = ''
'org.keepassxc.KeePassXC' = ''
'libreoffice-startcenter' = ''
'libreoffice-writer' = ''
'libreoffice-calc' = ''
'libreoffice-impress' = ''
'libreoffice-draw' = ''
'libreoffice-base' = ''
'soffice' = ''
'org.pwmt.zathura' = ''
'krita' = ''
'com.github.wwmm.easyeffects' = ''
'pavucontrol' = ''
'btop' = ''
'nmtui' = ''
