---
name: "Check mds for broken links"
# yamllint disable-line rule:truthy
on:
  - push
  - pull_request
jobs:
  broken_link_check:
    name: Run check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: true
