---
name: prettier
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - '**/*.css'
      - '**/*.json'
      - '.config/OpenRGB/plugins/settings/*'
      - '.config/waybar/config'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.css'
      - '**/*.json'
      - '.config/OpenRGB/plugins/settings/*'
      - '.config/waybar/config'
jobs:
  format_check:
    name: Check CSS/json/etc files with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: "**/{.css,*.json,*.md,.js}"
