---
name: prettier
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    paths:
      - '**/*.css'
      - '**/*.json'
      - '**/*.html'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.css'
      - '**/*.json'
      - '**/*.html'
jobs:
  format_check:
    name: Check CSS/json/etc files with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: >
            "**/{*.css,*.json,*.html}" --check
