---
name: Spellcheck
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
jobs:
  check:
    name: Spellcheck project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Spellcheck run
        uses: rojopolis/spellcheck-github-actions@0.43.0
